### ISSUE TITLE
waf update doesn't work at all

### ISSUE THREAD

**Issue by rr-** [waf-project/waf#1589]
rr-@tornado:~/src/CRC-manipulator$ ./waf --help
    waf [commands] [options]

    Main commands (example: ./waf build -j4)
    (...)
      update   : updates the plugins from the *waflib/extras* directory

So I run `./waf update`...

    rr-@tornado:~/src/CRC-manipulator$ ./waf update

and this is what I get:

    Traceback (most recent call last):
      File "/home/rr-/src/CRC-manipulator/.waf3-1.8.9-5cbbe70d5a6f2703c8c504d9ae23b252/waflib/Scripting.py", line 103, in waf_entry_point
        run_commands()
      File "/home/rr-/src/CRC-manipulator/.waf3-1.8.9-5cbbe70d5a6f2703c8c504d9ae23b252/waflib/Scripting.py", line 164, in run_commands
        ctx=run_command(cmd_name)
      File "/home/rr-/src/CRC-manipulator/.waf3-1.8.9-5cbbe70d5a6f2703c8c504d9ae23b252/waflib/Scripting.py", line 155, in run_command
        ctx.execute()
      File "/home/rr-/src/CRC-manipulator/.waf3-1.8.9-5cbbe70d5a6f2703c8c504d9ae23b252/waflib/Context.py", line 92, in execute
        self.recurse([os.path.dirname(g_module.root_path)])
      File "/home/rr-/src/CRC-manipulator/.waf3-1.8.9-5cbbe70d5a6f2703c8c504d9ae23b252/waflib/Context.py", line 133, in recurse
        user_function(self)
      File "/home/rr-/src/CRC-manipulator/.waf3-1.8.9-5cbbe70d5a6f2703c8c504d9ae23b252/waflib/Scripting.py", line 360, in update
        Configure.download_tool(tool,force=True,ctx=ctx)
    AttributeError: 'module' object has no attribute 'download_tool'

Version:

    rr-@tornado:~/src/CRC-manipulator$ ./waf --version
    waf 1.8.9 (06e49b2a82166aeb14dde8357c58387f252fc722)

**Comment by rr-** [comment]
This was broken in c427ab45af0585953298eec08125292b88d29b0c.

**Comment by ita1024** [comment]
Duplicate of https://github.com/waf-project/waf/issues/1541

It is too late to remove the command from waf 1.8 (no API changes).

**Comment by ita1024** [comment]
The command is now hidden in 2413ceea85e90d6653245e97bcb0b34da7e53d3d
