### ISSUE TITLE
mpv build failure due to change in waf.

### ISSUE THREAD

**Issue by orbea** [waf-project/waf#2032]
OS: `Slackware64-current`
`gcc-7.2.0`
`glibc-2.26`

After commit _____ I can no longer build mpv with waf, here is the build error.
```
[231/439] Compiling video/image_loader.c
[232/439] Compiling osdep/subprocess.c
[233/439] Compiling osdep/terminal-unix.c
[234/439] Linking build/mpv
[235/439] Compiling video/out/vo_drm.c
/usr/lib64/gcc/x86_64-slackware-linux/7.2.0/../../../../x86_64-slackware-linux/bin/ld: osdep/threads.c.18.o: undefined reference to symbol 'pthread_setname_np@@GLIBC_2.12'
/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

* Node /tmp/SBo/mpv/build/mpv.def is created more than once. The task generators are:
  1. 'mpv' in /tmp/SBo/mpv
  2. 'mpv' in /tmp/SBo/mpv
If you think that this is an error, set no_errcheck_out on the task instance
Waf: Leaving directory `/tmp/SBo/mpv/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
```
Full build log: https://pastebin.com/AESrf805

Git bisect results.
```
fa145ed65395d6c2c2f15ea54398aa010d91306f is the first bad commit
commit fa145ed65395d6c2c2f15ea54398aa010d91306f
Author: Thomas Nagy <tnagy@waf.io>
Date:   Thu Jan 5 03:44:36 2017 +0100

    Find the order that follows the alphabet

:040000 040000 e389f2f1465c382b8ab22c110e30536ad1cbd041 a9af31df9370f0d2570c7ea4c573e97cfda2e70d M	tests
:040000 040000 2cc8b72af54a9b27999858b5d4c0ab695f6bf7c0 2c22ec114b393c337c22a2fb0f11fa78e73da253 M	waflib
```
fa145ed65395d6c2c2f15ea54398aa010d91306f

Please see this mpv issue for more information.
https://github.com/mpv-player/mpv/issues/4894

**Comment by orbea** [comment]
config.log - https://pastebin.com/6U1ZtvGS

**Comment by ita1024** [comment]
The syms.py has changed quite a lot, so i am not sure that you want to use the updated version. Read the mpv ticket.

**Comment by orbea** [comment]
Thanks for your reply, I was not sure if this was a waf or mpv issue given this started with a change in waf.

**Comment by ita1024** [comment]
That is your fault actually. Use the waf version that is provided by mpv.

**Comment by orbea** [comment]
Mpv not building with a modern and maintained waf version is certainly not my fault and a valid issue.
