### ISSUE TITLE
Ifort Tool on Windows does not work in 1.8

### ISSUE THREAD

**Issue by haraldkl** [waf-project/waf#1690]
Looks like I only checked with the 1.9 branch from some point onwards. On the 1.8 branch the ifort tool on windows seems to be broken and throws this error when trying to build the simple fortran application:

    File "C:\Users\me\Documents\apes\aotus\waf3-1.8.18-292a1f1af8042be0d1c395c983de3789\waflib\Tools\ifort.py", line 409, in exec_command_ifort
        kw['cwd']=self.get_cwd()
    AttributeError: 'fcprogram' object has no attribute 'get_cwd'

**Comment by ita1024** [comment]
Update after f14a6d43092d3419d90c1ce16b9d3c700309d7b3
