### ISSUE TITLE
AttributeError when using winres

### ISSUE THREAD

**Issue by jhasse** [waf-project/waf#1759]
Using waf 1.9-pre3 I'm getting

```sh
Build failed
Traceback (most recent call last):
  File "/c/Users/jhasse/Desktop/pwcalculator/.waf3-1.9.0-e0b79117ac3d8ed2b901384fc559702f/waflib/Runner.py", line 128, in task_status
    return tsk.runnable_status()
  File "/c/Users/jhasse/Desktop/pwcalculator/.waf3-1.9.0-e0b79117ac3d8ed2b901384fc559702f/waflib/Task.py", line 305, in runnable_status
    new_sig=self.signature()
  File "/c/Users/jhasse/Desktop/pwcalculator/.waf3-1.9.0-e0b79117ac3d8ed2b901384fc559702f/waflib/Task.py", line 295, in signature
    self.sig_implicit_deps()
  File "/c/Users/jhasse/Desktop/pwcalculator/.waf3-1.9.0-e0b79117ac3d8ed2b901384fc559702f/waflib/Task.py", line 384, in sig_implicit_deps
    (bld.node_deps[key],bld.raw_deps[key])=self.scan()
  File "/c/Users/jhasse/Desktop/pwcalculator/.waf3-1.9.0-e0b79117ac3d8ed2b901384fc559702f/waflib/Tools/winres.py", line 66, in scan
    tmp.start(self.inputs[0],self.env)
  File "/c/Users/jhasse/Desktop/pwcalculator/.waf3-1.9.0-e0b79117ac3d8ed2b901384fc559702f/waflib/Tools/c_preproc.py", line 534, in start
    self.addlines(node)
  File "/c/Users/jhasse/Desktop/pwcalculator/.waf3-1.9.0-e0b79117ac3d8ed2b901384fc559702f/waflib/Tools/winres.py", line 40, in addlines
    pc=self.parse_cache
AttributeError: 'rc_parser' object has no attribute 'parse_cache'
```

when using `winres` like this: https://github.com/jhasse/pwcalculator/blob/7193c11d863ef95aaf4c643049cd8cce4fd48b36/wscript

It works fine with waf 1.8.21. If you want, I can bisect between the two, but maybe you already have an idea what might be the problem.

**Comment by ita1024** [comment]
It is a typo that was fixed a while ago. Use the latest from the waf-1.9 branch https://github.com/waf-project/waf/tree/waf-1.9

**Comment by jhasse** [comment]
I see, thanks! :)
